name: Simple CI Example
run-name: ci running

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: code loaded
        uses: actions/checkout@v3

      - name: Check check
        run: |
          echo "code checking..."
          ls -la
          echo "CI suckcess!"

      - name: Python code checking
        run: python main.py




